global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    moniker: "{VALIDATOR_MONIKER}"
    chain: "{CHAIN_ID}"


web:
  listen_address: "0.0.0.0:{PROMETHEUS_UI_PORT}"  # Set your desired IP and port here

# Remote write configuration to send metrics to your central Prometheus
remote_write:
  - url: "{REMOTE_WRITE_URL}"
    # Optional: add authentication if needed
    # basic_auth:
    #   username: "{REMOTE_WRITE_USERNAME}"
    #   password: "{REMOTE_WRITE_PASSWORD}"

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['{NODE_EXPORTER_HOST}:9100']
        labels:
          instance: "{VALIDATOR_MONIKER}"
          environment: cosmos-validator

  - job_name: 'cosmos'
    static_configs:
      - targets: ['host.docker.internal:{PROMETHEUS_PORT}']
        labels:
          instance: "{VALIDATOR_MONIKER}"
          environment: cosmos-validator
