global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs: []
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['prometheus:9090']
# 
#   - job_name: 'node-exporter'
#     static_configs:
#       - targets: ['node-exporter:9100']
# 
#   # Add your Cosmos node metrics endpoint here if it exposes Prometheus metrics
#   - job_name: 'cosmos-node'
#     static_configs:
#       - targets: ['host.docker.internal:26660']
#     metrics_path: /metrics
